site_name: notes
docs_dir: src
site_dir: out

theme:
  theme:
  name: readthedocs
  collapse_navigation: true   # enable collapsing
  navigation_depth: 3       # show nested levels (must be >1)
  sticky_navigation: true   
  highlightjs: true
  hljs_languages:
    - yaml
    - rust

nav:
  - Home: index.md
  - Math:
    - proof: math/proof-writing.md
  - CSE574:
      - 1: CSE574/1.md
  - CSE590:
      - 1: CSE590/1.md
